# French String Data (Built with -DFRENCH)

module Doocr
  D_DEVSTR = "MODE DEVELOPPEMENT ON.\n"
  D_CDROM  = "VERSION CD-ROM: DEFAULT.CFG DANS C:\\DOOMDATA\n"

  PRESSKEY  = "APPUYEZ SUR UNE TOUCHE."
  PRESSYN   = "APPUYEZ SUR Y OU N"
  QUITMSG   = "VOUS VOULEZ VRAIMENT\nQUITTER CE SUPER JEU?"
  LOADNET   = "VOUS NE POUVEZ PAS CHARGER\nUN JEU EN RESEAU!\n\n" + PRESSKEY
  QLOADNET  = "CHARGEMENT RAPIDE INTERDIT EN RESEAU!\n\n" + PRESSKEY
  QSAVESPOT = "VOUS N'AVEZ PAS CHOISI UN EMPLACEMENT!\n\n" + PRESSKEY
  SAVEDEAD  = "VOUS NE POUVEZ PAS SAUVER SI VOUS NE JOUEZ " \
              "PAS!\n\n" + PRESSKEY
  QSPROMPT = "SAUVEGARDE RAPIDE DANS LE FICHIER \n\n'%s'?\n\n" + PRESSYN
  QLPROMPT = "VOULEZ-VOUS CHARGER LA SAUVEGARDE" \
             "\n\n'%s'?\n\n" + PRESSYN
  NEWGAME = "VOUS NE POUVEZ PAS LANCER\n" \
            "UN NOUVEAU JEU SUR RESEAU.\n\n" + PRESSKEY
  NIGHTMARE = "VOUS CONFIRMEZ? CE NIVEAU EST\n" \
              "VRAIMENT IMPITOYABLE!n" + PRESSYN
  SWSTRING = "CECI EST UNE VERSION SHAREWARE DE DOOM.\n\n" \
             "VOUS DEVRIEZ COMMANDER LA TRILOGIE COMPLETE.\n\n" + PRESSKEY
  MSGOFF = "MESSAGES OFF"
  MSGON  = "MESSAGES ON"
  NETEND = "VOUS NE POUVEZ PAS METTRE FIN A UN JEU SUR " \
           "RESEAU!\n\n" + PRESSKEY
  ENDGAME = "VOUS VOULEZ VRAIMENT METTRE FIN AU JEU?\n\n" + PRESSYN

  DOSY = "(APPUYEZ SUR Y POUR REVENIR AU OS.)"

  DETAILHI    = "GRAPHISMES MAXIMUM "
  DETAILLO    = "GRAPHISMES MINIMUM "
  GAMMALVL0   = "CORRECTION GAMMA OFF"
  GAMMALVL1   = "CORRECTION GAMMA NIVEAU 1"
  GAMMALVL2   = "CORRECTION GAMMA NIVEAU 2"
  GAMMALVL3   = "CORRECTION GAMMA NIVEAU 3"
  GAMMALVL4   = "CORRECTION GAMMA NIVEAU 4"
  EMPTYSTRING = "EMPLACEMENT VIDE"

  GOTARMOR    = "ARMURE RECUPEREE."
  GOTMEGA     = "MEGA-ARMURE RECUPEREE!"
  GOTHTHBONUS = "BONUS DE SANTE RECUPERE."
  GOTARMBONUS = "BONUS D'ARMURE RECUPERE."
  GOTSTIM     = "STIMPACK RECUPERE."
  GOTMEDINEED = "MEDIKIT RECUPERE. VOUS EN AVEZ VRAIMENT BESOIN!"
  GOTMEDIKIT  = "MEDIKIT RECUPERE."
  GOTSUPER    = "SUPERCHARGE!"

  GOTBLUECARD = "CARTE MAGNETIQUE BLEUE RECUPEREE."
  GOTYELWCARD = "CARTE MAGNETIQUE JAUNE RECUPEREE."
  GOTREDCARD  = "CARTE MAGNETIQUE ROUGE RECUPEREE."
  GOTBLUESKUL = "CLEF CRANE BLEUE RECUPEREE."
  GOTYELWSKUL = "CLEF CRANE JAUNE RECUPEREE."
  GOTREDSKULL = "CLEF CRANE ROUGE RECUPEREE."

  GOTINVUL   = "INVULNERABILITE!"
  GOTBERSERK = "BERSERK!"
  GOTINVIS   = "INVISIBILITE PARTIELLE "
  GOTSUIT    = "COMBINAISON ANTI-RADIATIONS "
  GOTMAP     = "CARTE INFORMATIQUE "
  GOTVISOR   = "VISEUR A AMPLIFICATION DE LUMIERE "
  GOTMSPHERE = "MEGASPHERE!"

  GOTCLIP     = "CHARGEUR RECUPERE."
  GOTCLIPBOX  = "BOITE DE BALLES RECUPEREE."
  GOTROCKET   = "ROQUETTE RECUPEREE."
  GOTROCKBOX  = "CAISSE DE ROQUETTES RECUPEREE."
  GOTCELL     = "CELLULE D'ENERGIE RECUPEREE."
  GOTCELLBOX  = "PACK DE CELLULES D'ENERGIE RECUPERE."
  GOTSHELLS   = "4 CARTOUCHES RECUPEREES."
  GOTSHELLBOX = "BOITE DE CARTOUCHES RECUPEREE."
  GOTBACKPACK = "SAC PLEIN DE MUNITIONS RECUPERE!"

  GOTBFG9000  = "VOUS AVEZ UN BFG9000!  OH, OUI!"
  GOTCHAINGUN = "VOUS AVEZ LA MITRAILLEUSE!"
  GOTCHAINSAW = "UNE TRONCONNEUSE!"
  GOTLAUNCHER = "VOUS AVEZ UN LANCE-ROQUETTES!"
  GOTPLASMA   = "VOUS AVEZ UN FUSIL A PLASMA!"
  GOTSHOTGUN  = "VOUS AVEZ UN FUSIL!"
  GOTSHOTGUN2 = "VOUS AVEZ UN SUPER FUSIL!"

  PD_BLUEO   = "IL VOUS FAUT UNE CLEF BLEUE"
  PD_REDO    = "IL VOUS FAUT UNE CLEF ROUGE"
  PD_YELLOWO = "IL VOUS FAUT UNE CLEF JAUNE"
  PD_BLUEK   = PD_BLUEO
  PD_REDK    = PD_REDO
  PD_YELLOWK = PD_YELLOWO

  GGSAVED = "JEU SAUVEGARDE."

  HUSTR_MSGU = "[MESSAGE NON ENVOYE]"

  HUSTR_E1M1 = "E1M1: HANGAR"
  HUSTR_E1M2 = "E1M2: USINE NUCLEAIRE "
  HUSTR_E1M3 = "E1M3: RAFFINERIE DE TOXINES "
  HUSTR_E1M4 = "E1M4: CENTRE DE CONTROLE "
  HUSTR_E1M5 = "E1M5: LABORATOIRE PHOBOS "
  HUSTR_E1M6 = "E1M6: TRAITEMENT CENTRAL "
  HUSTR_E1M7 = "E1M7: CENTRE INFORMATIQUE "
  HUSTR_E1M8 = "E1M8: ANOMALIE PHOBOS "
  HUSTR_E1M9 = "E1M9: BASE MILITAIRE "

  HUSTR_E2M1 = "E2M1: ANOMALIE DEIMOS "
  HUSTR_E2M2 = "E2M2: ZONE DE CONFINEMENT "
  HUSTR_E2M3 = "E2M3: RAFFINERIE"
  HUSTR_E2M4 = "E2M4: LABORATOIRE DEIMOS "
  HUSTR_E2M5 = "E2M5: CENTRE DE CONTROLE "
  HUSTR_E2M6 = "E2M6: HALLS DES DAMNES "
  HUSTR_E2M7 = "E2M7: CUVES DE REPRODUCTION "
  HUSTR_E2M8 = "E2M8: TOUR DE BABEL "
  HUSTR_E2M9 = "E2M9: FORTERESSE DU MYSTERE "

  HUSTR_E3M1 = "E3M1: DONJON DE L'ENFER "
  HUSTR_E3M2 = "E3M2: BOURBIER DU DESESPOIR "
  HUSTR_E3M3 = "E3M3: PANDEMONIUM"
  HUSTR_E3M4 = "E3M4: MAISON DE LA DOULEUR "
  HUSTR_E3M5 = "E3M5: CATHEDRALE PROFANE "
  HUSTR_E3M6 = "E3M6: MONT EREBUS"
  HUSTR_E3M7 = "E3M7: LIMBES"
  HUSTR_E3M8 = "E3M8: DIS"
  HUSTR_E3M9 = "E3M9: CLAPIERS"

  HUSTR_1  = "NIVEAU 1: ENTREE "
  HUSTR_2  = "NIVEAU 2: HALLS SOUTERRAINS "
  HUSTR_3  = "NIVEAU 3: LE FEU NOURRI "
  HUSTR_4  = "NIVEAU 4: LE FOYER "
  HUSTR_5  = "NIVEAU 5: LES EGOUTS "
  HUSTR_6  = "NIVEAU 6: LE BROYEUR "
  HUSTR_7  = "NIVEAU 7: L'HERBE DE LA MORT"
  HUSTR_8  = "NIVEAU 8: RUSES ET PIEGES "
  HUSTR_9  = "NIVEAU 9: LE PUITS "
  HUSTR_10 = "NIVEAU 10: BASE DE RAVITAILLEMENT "
  HUSTR_11 = "NIVEAU 11: LE CERCLE DE LA MORT!"

  HUSTR_12 = "NIVEAU 12: L'USINE "
  HUSTR_13 = "NIVEAU 13: LE CENTRE VILLE"
  HUSTR_14 = "NIVEAU 14: LES ANTRES PROFONDES "
  HUSTR_15 = "NIVEAU 15: LA ZONE INDUSTRIELLE "
  HUSTR_16 = "NIVEAU 16: LA BANLIEUE"
  HUSTR_17 = "NIVEAU 17: LES IMMEUBLES"
  HUSTR_18 = "NIVEAU 18: LA COUR "
  HUSTR_19 = "NIVEAU 19: LA CITADELLE "
  HUSTR_20 = "NIVEAU 20: JE T'AI EU!"

  HUSTR_21 = "NIVEAU 21: LE NIRVANA"
  HUSTR_22 = "NIVEAU 22: LES CATACOMBES "
  HUSTR_23 = "NIVEAU 23: LA GRANDE FETE "
  HUSTR_24 = "NIVEAU 24: LE GOUFFRE "
  HUSTR_25 = "NIVEAU 25: LES CHUTES DE SANG"
  HUSTR_26 = "NIVEAU 26: LES MINES ABANDONNEES "
  HUSTR_27 = "NIVEAU 27: CHEZ LES MONSTRES "
  HUSTR_28 = "NIVEAU 28: LE MONDE DE L'ESPRIT "
  HUSTR_29 = "NIVEAU 29: LA LIMITE "
  HUSTR_30 = "NIVEAU 30: L'ICONE DU PECHE "

  HUSTR_31 = "NIVEAU 31: WOLFENSTEIN"
  HUSTR_32 = "NIVEAU 32: LE MASSACRE"

  HUSTR_CHATMACRO1 = "JE SUIS PRET A LEUR EN FAIRE BAVER!"
  HUSTR_CHATMACRO2 = "JE VAIS BIEN."
  HUSTR_CHATMACRO3 = "JE N'AI PAS L'AIR EN FORME!"
  HUSTR_CHATMACRO4 = "AU SECOURS!"
  HUSTR_CHATMACRO5 = "TU CRAINS!"
  HUSTR_CHATMACRO6 = "LA PROCHAINE FOIS, MINABLE..."
  HUSTR_CHATMACRO7 = "VIENS ICI!"
  HUSTR_CHATMACRO8 = "JE VAIS M'EN OCCUPER."
  HUSTR_CHATMACRO9 = "OUI"
  HUSTR_CHATMACRO0 = "NON"

  HUSTR_TALKTOSELF1 = "VOUS PARLEZ TOUT SEUL "
  HUSTR_TALKTOSELF2 = "QUI EST LA?"
  HUSTR_TALKTOSELF3 = "VOUS VOUS FAITES PEUR "
  HUSTR_TALKTOSELF4 = "VOUS COMMENCEZ A DELIRER "
  HUSTR_TALKTOSELF5 = "VOUS ETES LARGUE..."

  HUSTR_MESSAGESENT = "[MESSAGE ENVOYE]"

  HUSTR_PLRGREEN  = "VERT: "
  HUSTR_PLRINDIGO = "INDIGO: "
  HUSTR_PLRBROWN  = "BRUN: "
  HUSTR_PLRRED    = "ROUGE: "

  HUSTR_KEYGREEN  = 'g' # french key should be "V"
  HUSTR_KEYINDIGO = 'i'
  HUSTR_KEYBROWN  = 'b'
  HUSTR_KEYRED    = 'r'

  AMSTR_FOLLOWON  = "MODE POURSUITE ON"
  AMSTR_FOLLOWOFF = "MODE POURSUITE OFF"

  AMSTR_GRIDON  = "GRILLE ON"
  AMSTR_GRIDOFF = "GRILLE OFF"

  AMSTR_MARKEDSPOT   = "REPERE MARQUE "
  AMSTR_MARKSCLEARED = "REPERES EFFACES "

  STSTR_MUS    = "CHANGEMENT DE MUSIQUE "
  STSTR_NOMUS  = "IMPOSSIBLE SELECTION"
  STSTR_DQDON  = "INVULNERABILITE ON "
  STSTR_DQDOFF = "INVULNERABILITE OFF"

  STSTR_KFAADDED = "ARMEMENT MAXIMUM! "
  STSTR_FAADDED  = "ARMES (SAUF CLEFS) AJOUTEES"

  STSTR_NCON  = "BARRIERES ON"
  STSTR_NCOFF = "BARRIERES OFF"

  STSTR_BEHOLD  = " inVuln, Str, Inviso, Rad, Allmap, or Lite-amp"
  STSTR_BEHOLDX = "AMELIORATION ACTIVEE"

  STSTR_CHOPPERS = "... DOESN'T SUCK - GM"
  STSTR_CLEV     = "CHANGEMENT DE NIVEAU..."

  E1TEXT = "APRES AVOIR VAINCU LES GROS MECHANTS\n" \
           "ET NETTOYE LA BASE LUNAIRE, VOUS AVEZ\n" \
           "GAGNE, NON? PAS VRAI? OU EST DONC VOTRE\n" \
           " RECOMPENSE ET VOTRE BILLET DE\n" \
           "RETOUR? QU'EST-QUE CA VEUT DIRE?CE" \
           "N'EST PAS LA FIN ESPEREE!\n" \
           "\n" \
           "CA SENT LA VIANDE PUTREFIEE, MAIS\n" \
           "ON DIRAIT LA BASE DEIMOS. VOUS ETES\n" \
           "APPAREMMENT BLOQUE AUX PORTES DE L'ENFER.\n" \
           "LA SEULE ISSUE EST DE L'AUTRE COTE.\n" \
           "\n" \
           "POUR VIVRE LA SUITE DE DOOM, JOUEZ\n" \
           "A 'AUX PORTES DE L'ENFER' ET A\n" \
           "L'EPISODE SUIVANT, 'L'ENFER'!\n"

  E2TEXT = "VOUS AVEZ REUSSI. L'INFAME DEMON\n" \
           "QUI CONTROLAIT LA BASE LUNAIRE DE\n" \
           "DEIMOS EST MORT, ET VOUS AVEZ\n" \
           "TRIOMPHE! MAIS... OU ETES-VOUS?\n" \
           "VOUS GRIMPEZ JUSQU'AU BORD DE LA\n" \
           "LUNE ET VOUS DECOUVREZ L'ATROCE\n" \
           "VERITE.\n" \
           "\n" \
           "DEIMOS EST AU-DESSUS DE L'ENFER!\n" \
           "VOUS SAVEZ QUE PERSONNE NE S'EN\n" \
           "EST JAMAIS ECHAPPE, MAIS CES FUMIERS\n" \
           "VONT REGRETTER DE VOUS AVOIR CONNU!\n" \
           "VOUS REDESCENDEZ RAPIDEMENT VERS\n" \
           "LA SURFACE DE L'ENFER.\n" \
           "\n" \
           "VOICI MAINTENANT LE CHAPITRE FINAL DE\n" \
           "DOOM! -- L'ENFER."

  E3TEXT = "LE DEMON ARACHNEEN ET REPUGNANT\n" \
           "QUI A DIRIGE L'INVASION DES BASES\n" \
           "LUNAIRES ET SEME LA MORT VIENT DE SE\n" \
           "FAIRE PULVERISER UNE FOIS POUR TOUTES.\n" \
           "\n" \
           "UNE PORTE SECRETE S'OUVRE. VOUS ENTREZ.\n" \
           "VOUS AVEZ PROUVE QUE VOUS POUVIEZ\n" \
           "RESISTER AUX HORREURS DE L'ENFER.\n" \
           "IL SAIT ETRE BEAU JOUEUR, ET LORSQUE\n" \
           "VOUS SORTEZ, VOUS REVOYEZ LES VERTES\n" \
           "PRAIRIES DE LA TERRE, VOTRE PLANETE.\n" \
           "\n" \
           "VOUS VOUS DEMANDEZ CE QUI S'EST PASSE\n" \
           "SUR TERRE PENDANT QUE VOUS AVEZ\n" \
           "COMBATTU LE DEMON. HEUREUSEMENT,\n" \
           "AUCUN GERME DU MAL N'A FRANCHI\n" \
           "CETTE PORTE AVEC VOUS..."

  C1TEXT = "VOUS ETES AU PLUS PROFOND DE L'ASTROPORT\n" \
           "INFESTE DE MONSTRES, MAIS QUELQUE CHOSE\n" \
           "NE VA PAS. ILS ONT APPORTE LEUR PROPRE\n" \
           "REALITE, ET LA TECHNOLOGIE DE L'ASTROPORT\n" \
           "EST AFFECTEE PAR LEUR PRESENCE.\n" \
           "\n" \
           "DEVANT VOUS, VOUS VOYEZ UN POSTE AVANCE\n" \
           "DE L'ENFER, UNE ZONE FORTIFIEE. SI VOUS\n" \
           "POUVEZ PASSER, VOUS POURREZ PENETRER AU\n" \
           "COEUR DE LA BASE HANTEE ET TROUVER \n" \
           "L'INTERRUPTEUR DE CONTROLE QUI GARDE LA \n" \
           "POPULATION DE LA TERRE EN OTAGE."

  C2TEXT = "VOUS AVEZ GAGNE! VOTRE VICTOIRE A PERMIS\n" \
           "A L'HUMANITE D'EVACUER LA TERRE ET \n" \
           "D'ECHAPPER AU CAUCHEMAR. VOUS ETES \n" \
           "MAINTENANT LE DERNIER HUMAIN A LA SURFACE \n" \
           "DE LA PLANETE. VOUS ETES ENTOURE DE \n" \
           "MUTANTS CANNIBALES, D'EXTRATERRESTRES \n" \
           "CARNIVORES ET D'ESPRITS DU MAL. VOUS \n" \
           "ATTENDEZ CALMEMENT LA MORT, HEUREUX \n" \
           "D'AVOIR PU SAUVER VOTRE RACE.\n" \
           "MAIS UN MESSAGE VOUS PARVIENT SOUDAIN\n" \
           "DE L'ESPACE: \"NOS CAPTEURS ONT LOCALISE\n" \
           "LA SOURCE DE L'INVASION EXTRATERRESTRE.\n" \
           "SI VOUS Y ALLEZ, VOUS POURREZ PEUT-ETRE\n" \
           "LES ARRETER. LEUR BASE EST SITUEE AU COEUR\n" \
           "DE VOTRE VILLE NATALE, PRES DE L'ASTROPORT.\n" \
           "VOUS VOUS RELEVEZ LENTEMENT ET PENIBLEMENT\n" \
           "ET VOUS REPARTEZ POUR LE FRONT."

  C3TEXT = "VOUS ETES AU COEUR DE LA CITE CORROMPUE,\n" \
           "ENTOURE PAR LES CADAVRES DE VOS ENNEMIS.\n" \
           "VOUS NE VOYEZ PAS COMMENT DETRUIRE LA PORTE\n" \
           "DES CREATURES DE CE COTE. VOUS SERREZ\n" \
           "LES DENTS ET PLONGEZ DANS L'OUVERTURE.\n" \
           "\n" \
           "IL DOIT Y AVOIR UN MOYEN DE LA FERMER\n" \
           "DE L'AUTRE COTE. VOUS ACCEPTEZ DE\n" \
           "TRAVERSER L'ENFER POUR LE FAIRE?"

  C4TEXT = "LE VISAGE HORRIBLE D'UN DEMON D'UNE\n" \
           "TAILLE INCROYABLE S'EFFONDRE DEVANT\n" \
           "VOUS LORSQUE VOUS TIREZ UNE SALVE DE\n" \
           "ROQUETTES DANS SON CERVEAU. LE MONSTRE\n" \
           "SE RATATINE, SES MEMBRES DECHIQUETES\n" \
           "SE REPANDANT SUR DES CENTAINES DE\n" \
           "KILOMETRES A LA SURFACE DE L'ENFER.\n" \
           "\n" \
           "VOUS AVEZ REUSSI. L'INVASION N'AURA.\n" \
           "PAS LIEU. LA TERRE EST SAUVEE. L'ENFER\n" \
           "EST ANEANTI. EN VOUS DEMANDANT OU IRONT\n" \
           "MAINTENANT LES DAMNES, VOUS ESSUYEZ\n" \
           "VOTRE FRONT COUVERT DE SUEUR ET REPARTEZ\n" \
           "VERS LA TERRE. SA RECONSTRUCTION SERA\n" \
           "BEAUCOUP PLUS DROLE QUE SA DESTRUCTION.\n"

  C5TEXT = "FELICITATIONS! VOUS AVEZ TROUVE LE\n" \
           "NIVEAU SECRET! IL SEMBLE AVOIR ETE\n" \
           "CONSTRUIT PAR LES HUMAINS. VOUS VOUS\n" \
           "DEMANDEZ QUELS PEUVENT ETRE LES\n" \
           "HABITANTS DE CE COIN PERDU DE L'ENFER."

  C6TEXT = "FELICITATIONS! VOUS AVEZ DECOUVERT\n" \
           "LE NIVEAU SUPER SECRET! VOUS FERIEZ\n" \
           "MIEUX DE FONCER DANS CELUI-LA!\n"

  CC_ZOMBIE  = "ZOMBIE"
  CC_SHOTGUN = "TYPE AU FUSIL"
  CC_HEAVY   = "MEC SUPER-ARME"
  CC_IMP     = "DIABLOTIN"
  CC_DEMON   = "DEMON"
  CC_LOST    = "AME PERDUE"
  CC_CACO    = "CACODEMON"
  CC_HELL    = "CHEVALIER DE L'ENFER"
  CC_BARON   = "BARON DE L'ENFER"
  CC_ARACH   = "ARACHNOTRON"
  CC_PAIN    = "ELEMENTAIRE DE LA DOULEUR"
  CC_REVEN   = "REVENANT"
  CC_MANCU   = "MANCUBUS"
  CC_ARCH    = "ARCHI-INFAME"
  CC_SPIDER  = "L'ARAIGNEE CERVEAU"
  CC_CYBER   = "LE CYBERDEMON"
  CC_HERO    = "NOTRE HEROS"
end
