name: Ubuntu
on: [push, pull_request]
jobs:
  demos:
    name: Ubuntu Demos
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install X11 and graphical dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libgl1-mesa-dev xorg-dev
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Install Crystal libs
        run: shards install
      - name: Build project
        run: make
      - name: Run Demos
        run: |
          mv ./DOOM1.WAD ./bin/
          cd bin
          ./doo-cr -timedemo demo1 -headless -iwad DOOM1.WAD
          ./doo-cr -timedemo demo2 -headless -iwad DOOM1.WAD
          ./doo-cr -timedemo demo3 -headless -iwad DOOM1.WAD