name: Windows Artifact
on:
  push:
    branches: [ "master" ]
jobs:
  build:
    name: Windows Artifact
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Download source
        uses: actions/checkout@v4

      - name: Set up MSYS2 (UCRT64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-crystal
            mingw-w64-ucrt-x86_64-pkg-config
            mingw-w64-ucrt-x86_64-pcre2
            mingw-w64-ucrt-x86_64-libyaml
            mingw-w64-ucrt-x86_64-openssl
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-shards
            make
            git
      - name: Build project
        run: make
      - name: Package exe
        run: |
          mkdir -p dist
          cp DOOM1.WAD bin
          cp bin/* dist/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: doo-cr-windows
          path: dist/