name: Windows
on: [push, pull_request]
jobs:
  demos:
    name: Windows Demos
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Download source
        uses: actions/checkout@v4

      - name: Set up MSYS2 (UCRT64)
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-crystal
            mingw-w64-ucrt-x86_64-pkg-config
            mingw-w64-ucrt-x86_64-pcre2
            mingw-w64-ucrt-x86_64-libyaml
            mingw-w64-ucrt-x86_64-openssl
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-shards
            make
            git
      - name: Build project
        run: make
      - name: Run Demos
        run: |
          mv DOOM1.WAD ./bin
          cd bin
          ./doo-cr.exe -timedemo demo1 -headless
          ./doo-cr.exe -timedemo demo2 -headless
          ./doo-cr.exe -timedemo demo3 -headless